node {
    stage('Git Clone') {
        dir ('MAVEN') {
            git 'https://github.com/cit31/studentapp-code.git'
        }
    }
    stage('Compile') {
        dir ('MAVEN') {
            sh 'mvn compile'
        }
    }
    stage('Sonar-Cloud') {
        dir ('MAVEN') {
            sh 'mvn sonar:sonar   -Dsonar.projectKey=studentapp   -Dsonar.organization=carreerit-github   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=3bdb39dc2936bfc7b8f62eac86ebcf26c89318e4'
        }
    }
    stage('Packaging') {
        dir ('MAVEN') {
            sh 'mvn package'
        }
    }
    stage('Deploy') {
        build job: 'Create_Instance_Ansible', parameters: [string(name: 'Hostname', value: 'stu-dev-app01'), booleanParam(name: 'INSTANCE_RECREATE', value: true)]
        dir ('ANSIBLE') {
            git 'https://github.com/cit31/ansible.git'
        sh '''
export ANSIBLE_CONFIG=/var/lib/jenkins/ansible.cfg
echo stu-dev-app01 >hosts
ansible-playbook -i hosts playbooks/deploy.yml
'''
        }
    }
    stage('Selenium-Tests') {
        dir ('SELENIUM') {
            git 'https://github.com/cit31/selenium-sauce.git'
            sh '''
IPADDRESS=$(gcloud compute instances list | grep stu-dev-app01 | awk '{print $5}')
sed -i -e "s/IPADDRESS/$IPADDRESS/" src/test/java/framework/CrudStudent.java
mvn clean install "-Dremote=true" "-DseleniumGridURL=http://raghudevops31:f57a36cd-7b3f-4227-9452-64b6fb1bdf23@ondemand.saucelabs.com:80/wd/hub"
'''
    }
}