node {
    stage('Git Clone') {
        dir ('MAVEN') {
            git 'https://github.com/cit31/studentapp-code.git'
        }
    }
    stage('Compile') {
        sh 'mvn compile'
    }
    stage('Sonar-Cloud') {
        sh 'mvn sonar:sonar   -Dsonar.projectKey=studentapp   -Dsonar.organization=carreerit-github   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=3bdb39dc2936bfc7b8f62eac86ebcf26c89318e4'
    }
    stage('Packaging') {
        sh 'mvn package'
    }
    stage('Deploy') {
        build job: 'Create_Instance_Ansible', parameters: [string(name: 'Hostname', value: 'studevapp01'), booleanParam(name: 'INSTANCE_RECREATE', value: true)]
        dir ('ANSIBLE') {
            git 'https://github.com/cit31/ansible.git'
        sh '''
ansible-playbook playbooks/deploy.yml
'''
        }
    }
}