node {
    stage('Git Clone') {
        git 'https://github.com/cit31/studentapp-code.git'
    }
    stage('Compile') {
        sh 'mvn compile'
    }
    stage('Sonar-Cloud') {
        sh 'mvn sonar:sonar   -Dsonar.projectKey=studentapp   -Dsonar.organization=carreerit-github   -Dsonar.host.url=https://sonarcloud.io   -Dsonar.login=3bdb39dc2936bfc7b8f62eac86ebcf26c89318e4'
    }
}